cmake_minimum_required(VERSION 3.21)
project(harbor_cad_filter LANGUAGES CXX HIP)
find_package(VTK REQUIRED COMPONENTS CommonCore CommonDataModel FiltersGeneral IOXML AcceleratorsVTKmFilters)
find_package(Kokkos 4.3 REQUIRED)
find_package(nlohmann_json REQUIRED)
find_package(tinyxml2 REQUIRED)
find_package(OpenSSL REQUIRED COMPONENTS Crypto)
find_package(hip REQUIRED)
add_executable(harbor-cad-filter filter.cpp)
set_source_files_properties(filter.cpp PROPERTIES LANGUAGE HIP)
target_compile_features(harbor-cad-filter PRIVATE cxx_std_17)
target_link_libraries(harbor-cad-filter PRIVATE ${VTK_LIBRARIES} Kokkos::kokkos nlohmann_json::nlohmann_json tinyxml2::tinyxml2 OpenSSL::Crypto hip::host)
vtk_module_autoinit(TARGETS harbor-cad-filter MODULES ${VTK_LIBRARIES})
install(TARGETS harbor-cad-filter RUNTIME DESTINATION bin)
